# Generated by Django 4.2.28 on 2026-02-17 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='施設名')),
                ('prefecture', models.CharField(max_length=50, verbose_name='都道府県')),
                ('address', models.TextField(verbose_name='住所')),
                ('category', models.CharField(max_length=100, verbose_name='施設カテゴリ')),
                ('external_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
            ],
            options={
                'verbose_name': '施設',
                'verbose_name_plural': '施設一覧',
            },
        ),
        migrations.CreateModel(
            name='WirelessEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=100, verbose_name='メーカー')),
                ('model_name', models.CharField(max_length=100, verbose_name='型番')),
                ('min_frequency', models.DecimalField(decimal_places=3, max_digits=7, verbose_name='最小周波数(MHz)')),
                ('max_frequency', models.DecimalField(decimal_places=3, max_digits=7, verbose_name='最大周波数(MHz)')),
            ],
            options={
                'verbose_name': 'ワイヤレス機器',
                'verbose_name_plural': 'ワイヤレス機器一覧',
            },
        ),
        migrations.CreateModel(
            name='TVChannelStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_number', models.IntegerField(verbose_name='チャンネル番号')),
                ('is_available', models.BooleanField(default=True, verbose_name='空き状況')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='facilities.facility')),
            ],
            options={
                'verbose_name': 'TVチャンネル状態',
                'verbose_name_plural': 'TVチャンネル状態一覧',
                'ordering': ['channel_number'],
                'unique_together': {('facility', 'channel_number')},
            },
        ),
    ]
