# Generated by Django 4.2.28 on 2026-02-17 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wirelessequipment',
            name='max_frequency',
            field=models.PositiveIntegerField(verbose_name='最大周波数(kHz)'),
        ),
        migrations.AlterField(
            model_name='wirelessequipment',
            name='min_frequency',
            field=models.PositiveIntegerField(verbose_name='最小周波数(kHz)'),
        ),
    ]
