# Generated by Django 4.2.28 on 2026-02-17 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0002_alter_wirelessequipment_max_frequency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='external_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
