# Generated by Django 4.2.28 on 2026-02-17 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0003_alter_facility_external_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='applied_area',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='適用エリア'),
        ),
    ]
