# Generated by Django 4.2.28 on 2026-02-19 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0004_facility_applied_area'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facility',
            old_name='external_id',
            new_name='postal_code',
        ),
        migrations.AlterField(
            model_name='facility',
            name='postal_code',
            field=models.CharField(max_length=100, null=True, blank=True, verbose_name="郵便番号"),
        ),
    ]
