# Generated by Django 4.2.28 on 2026-02-24 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0005_rename_external_id_to_postal_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='applied_area',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='適用エリア'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='postal_code',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='郵便番号'),
        ),
    ]
