# Generated by Django 4.2.28 on 2026-02-18 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id_1', models.CharField(max_length=3, verbose_name='会員番号1')),
                ('member_id_2', models.CharField(max_length=4, verbose_name='会員番号2')),
                ('name', models.CharField(max_length=255, verbose_name='会員名')),
                ('department', models.CharField(blank=True, max_length=255, null=True, verbose_name='部署')),
                ('manager_name', models.CharField(max_length=255, verbose_name='運用担当者')),
                ('phone', models.CharField(max_length=20, verbose_name='Tel')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
            ],
            options={
                'verbose_name': '会社情報',
                'verbose_name_plural': '会社情報',
            },
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_address', models.EmailField(max_length=254, verbose_name='送信先アドレス')),
                ('from_address', models.EmailField(max_length=254, verbose_name='送信元アドレス')),
                ('subject', models.CharField(max_length=255, verbose_name='件名')),
                ('body', models.TextField(verbose_name='本文')),
            ],
            options={
                'verbose_name': 'メールテンプレート',
                'verbose_name_plural': 'メールテンプレート',
            },
        ),
        migrations.CreateModel(
            name='WoffUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255, unique=True, verbose_name='ユーザーID')),
                ('name', models.CharField(max_length=255, verbose_name='名前')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='メールアドレス')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='電話番号')),
            ],
            options={
                'verbose_name': 'WOFFユーザー',
                'verbose_name_plural': 'WOFFユーザー',
            },
        ),
    ]
