# Generated by Django 4.2.28 on 2026-02-19 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Company',
            new_name='Member',
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'verbose_name': '会員情報', 'verbose_name_plural': '会員情報'},
        ),
    ]
