# Generated by Django 4.2.28 on 2026-02-19 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_company_member_alter_member_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='member_id_1',
            field=models.CharField(max_length=3, verbose_name='会員番号'),
        ),
    ]
