# Generated by Django 4.2.28 on 2026-02-22 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_member_member_id_1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailtemplate',
            name='from_address',
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='cc_address',
            field=models.CharField(blank=True, default='', help_text='カンマ区切りで複数指定可能。{ユーザーEメールアドレス} も使用できます。', max_length=255, verbose_name='CC'),
        ),
        migrations.AlterField(
            model_name='member',
            name='department',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='部署'),
        ),
        migrations.AlterField(
            model_name='woffuser',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='メールアドレス'),
        ),
        migrations.AlterField(
            model_name='woffuser',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='電話番号'),
        ),
    ]
