# Generated by Django 4.2.28 on 2026-02-22 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_emailtemplate_from_address_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WoffUser',
        ),
    ]
