# Generated by Django 4.2.28 on 2026-02-24 10:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0005_delete_woffuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='OTPコード(ハッシュ)')),
                ('otp_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='OTP有効期限')),
                ('otp_attempts', models.IntegerField(default=0, verbose_name='試行回数')),
                ('otp_locked_until', models.DateTimeField(blank=True, null=True, verbose_name='ロック解除日時')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ユーザープロフィール',
                'verbose_name_plural': 'ユーザープロフィール',
            },
        ),
    ]
