# Generated by Django 4.2.28 on 2026-02-24 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='メールアドレス'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='family_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='姓'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='given_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='名'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='電話番号'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phonetic_family_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='姓(ふりがな)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phonetic_given_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='名(ふりがな)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', '管理者'), ('editor', '編集者'), ('general', '一般'), ('viewer', '閲覧者')], default='general', max_length=20, verbose_name='役割'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='otp_code',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='OTPコード(ハッシュ)'),
        ),
    ]
