# Generated by Django 4.2.28 on 2026-02-24 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='DropboxToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(default='backup', max_length=50, verbose_name='サービス名')),
                ('access_token', models.TextField(verbose_name='アクセストークン')),
                ('refresh_token', models.TextField(blank=True, null=True, verbose_name='リフレッシュトークン')),
                ('token_type', models.CharField(default='Bearer', max_length=20)),
                ('account_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='アカウントID')),
                ('account_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='アカウント名')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='有効期限')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dropboxトークン',
                'verbose_name_plural': 'Dropboxトークン',
            },
        ),
    ]
