# Generated by Django 4.2.28 on 2026-02-25 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_dropboxtoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='DropboxAuthHelper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '1. Dropbox連携を開始する',
                'verbose_name_plural': '1. Dropbox連携を開始する',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='dropboxtoken',
            name='service_name',
            field=models.CharField(default='backup', max_length=50, unique=True, verbose_name='サービス名'),
        ),
    ]
