# Generated by Django 4.2.28 on 2026-02-25 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_dropboxauthhelper_alter_dropboxtoken_service_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='name',
            field=models.CharField(default='default', help_text='識別用の名前（例: adjustment）。プログラムから参照されます。', max_length=50, unique=True, verbose_name='テンプレート名'),
        ),
    ]
