# Generated by Django 4.2.28 on 2026-03-02 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_userprofile_portal_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='otp_attempts',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='otp_code',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='otp_expires_at',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='otp_locked_until',
        ),
        migrations.AlterField(
            model_name='dropboxtoken',
            name='account_id',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='アカウントID'),
        ),
        migrations.AlterField(
            model_name='dropboxtoken',
            name='account_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='アカウント名'),
        ),
        migrations.AlterField(
            model_name='dropboxtoken',
            name='refresh_token',
            field=models.TextField(blank=True, default='', verbose_name='リフレッシュトークン'),
        ),
    ]
