# Generated by Django 4.2.28 on 2026-02-17 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facilities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100, verbose_name='申請者名')),
                ('event_name', models.CharField(blank=True, max_length=255, verbose_name='催事名')),
                ('event_date', models.DateField(verbose_name='使用日')),
                ('used_frequencies', models.JSONField(verbose_name='使用周波数リスト')),
                ('line_works_user_id', models.CharField(blank=True, max_length=100, verbose_name='LINE WORKSユーザーID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='facilities.facility', verbose_name='対象施設')),
            ],
            options={
                'verbose_name': '運用調整届',
                'verbose_name_plural': '運用調整届一覧',
            },
        ),
    ]
