# Generated by Django 4.2.28 on 2026-02-24 07:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('facilities', '0006_alter_facility_applied_area_and_more'),
        ('adjustments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operationadjustment',
            options={'ordering': ['-created_at'], 'verbose_name': '運用調整届', 'verbose_name_plural': '運用調整届一覧'},
        ),
        migrations.RemoveField(
            model_name='operationadjustment',
            name='event_date',
        ),
        migrations.RemoveField(
            model_name='operationadjustment',
            name='facility',
        ),
        migrations.RemoveField(
            model_name='operationadjustment',
            name='line_works_user_id',
        ),
        migrations.RemoveField(
            model_name='operationadjustment',
            name='used_frequencies',
        ),
        migrations.AddField(
            model_name='operationadjustment',
            name='app_type',
            field=models.CharField(choices=[('new', '新規'), ('change', '変更'), ('delete', '削除')], default='new', max_length=10, verbose_name='申請区分'),
        ),
        migrations.AddField(
            model_name='operationadjustment',
            name='event_comment',
            field=models.TextField(blank=True, max_length=165, verbose_name='コメント'),
        ),
        migrations.AddField(
            model_name='operationadjustment',
            name='extra_53ch',
            field=models.BooleanField(default=False, verbose_name='53ch併用'),
        ),
        migrations.AddField(
            model_name='operationadjustment',
            name='facilities',
            field=models.ManyToManyField(related_name='adjustments', to='facilities.facility', verbose_name='対象施設'),
        ),
        migrations.AddField(
            model_name='operationadjustment',
            name='facilities_json',
            field=models.JSONField(default=list, verbose_name='施設別日程データ'),
        ),
        migrations.AddField(
            model_name='operationadjustment',
            name='mic_counts_json',
            field=models.JSONField(default=dict, verbose_name='使用マイク数データ'),
        ),
        migrations.AddField(
            model_name='operationadjustment',
            name='selected_channels_json',
            field=models.JSONField(default=list, verbose_name='選択周波数データ'),
        ),
        migrations.AddField(
            model_name='operationadjustment',
            name='status',
            field=models.CharField(choices=[('draft', '下書き'), ('submitted', '送信済み')], default='draft', max_length=20, verbose_name='ステータス'),
        ),
        migrations.AddField(
            model_name='operationadjustment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日時'),
        ),
        migrations.AddField(
            model_name='operationadjustment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='作成者'),
        ),
        migrations.AddField(
            model_name='operationadjustment',
            name='user_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='メールアドレス'),
        ),
        migrations.AddField(
            model_name='operationadjustment',
            name='user_kana',
            field=models.CharField(blank=True, max_length=100, verbose_name='ふりがな'),
        ),
        migrations.AddField(
            model_name='operationadjustment',
            name='user_tel',
            field=models.CharField(blank=True, max_length=20, verbose_name='電話番号'),
        ),
        migrations.AlterField(
            model_name='operationadjustment',
            name='event_name',
            field=models.CharField(max_length=50, verbose_name='催事名'),
        ),
        migrations.AlterField(
            model_name='operationadjustment',
            name='user_name',
            field=models.CharField(max_length=100, verbose_name='氏名'),
        ),
    ]
