# Generated by Django 4.2.28 on 2026-02-26 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adjustments', '0002_alter_operationadjustment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationadjustment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='adjustments.operationadjustment', verbose_name='元申請'),
        ),
    ]
